backend/controllers/SocialActionController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Security;
use backend\models\SocialAction;

/**
 * Banners controller
 */
class SocialActionController extends Controller{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays page layout.
     *
     * @return string
     */
    public function actionIndex(){
		$searchModel = new SocialAction();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
        return $this->render('index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider
		]);
    }
	
	/**
     * Create new page layout.
     *
     * @return string
     */
    public function actionCreate($page_id='',$page='', $type=''){
		$model = new SocialAction();
		if(!empty($_POST['SocialAction'])){
			$model->attributes = $_POST['SocialAction'];
			if(!empty($_FILES['image']['name'])){
				$image_name = time().$_FILES['image']['name'];
				$image_tmp_name = $_FILES['image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'social/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->image = $image_name;
			}
			if(!empty($_FILES['mobile_image']['name'])){
				$image_name = time().$_FILES['mobile_image']['name'];
				$image_tmp_name = $_FILES['mobile_image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'social/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->mobile_image = $image_name;
			}
		
			$model->created_on = new \yii\db\Expression('now()');
			$model->created_by = Yii::$app->user->identity->id;
		
			if ($model->validate()) {
				$model->save();
				return $this->redirect(['/'.$page.'/update?id='.$page_id.'&type='.$type]);
			}		
		}		
        return $this->render('create', [
				'model' => $model
		]);
    }
	
	
	// update page layout
	public function actionUpdate($id='',$page_id='',$page='', $type=''){
		$model = $this->findModel($id);
		if(!empty($_POST['SocialAction'])){
			$model->attributes = $_POST['SocialAction'];
			$model->image = !empty($_POST['uploaded_image']) ? $_POST['uploaded_image'] : '';
			$model->mobile_image = !empty($_POST['uploaded_mobile_image']) ? $_POST['uploaded_mobile_image'] : '';
		
			if(!empty($_FILES['image']['name'])){
				$image_name = time().$_FILES['image']['name'];
				$image_tmp_name = $_FILES['image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'social/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->image = $image_name;
			}if(!empty($_FILES['mobile_image']['name'])){
				$image_name = time().$_FILES['mobile_image']['name'];
				$image_tmp_name = $_FILES['mobile_image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'social/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->mobile_image = $image_name;
			}
			$model->updated_on = new \yii\db\Expression('now()');
			$model->updated_by = Yii::$app->user->identity->id;
		
			if ($model->validate()) {
				$model->save();
				return $this->redirect(['/'.$page.'/update?id='.$page_id.'&type='.$type]);
			}
		}
		return $this->render('update', [
				'model' => $model,
				'id' => $id
		]);
    }
	
	protected function findModel($id) {
        if (($model = SocialAction::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

backend/views/social-action/create.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Social Action';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-10 col-lg-offset-1">
    <div class="panel panel-default">
         <div class="panel-heading">
            <?php echo $this->title ?>
            <div class="menuLink">
                <a href="<?php echo BASE_URL; ?><?= $_GET['page']; ?>/update?id=<?= $_GET['page_id']; ?>&type=social-action" title="Social Action List">
                    <i class="fa fa-list-ul fa-fw" style="font-size: 18px !important;"></i>
                </a>
            </div>
        </div>
        <div class="panel-body">
            <div class="row table-bordered">
                <?php
                $form = ActiveForm::begin([
                            'id' => 'content_form',
                            'options' => [
                                'enctype' => 'multipart/form-data',
                            ],
                                ]
                );
                ?>            

                    <div class="form-group">
                        <?= $form->field($model, 'sec_heading')->textInput() ?>      
                    </div>
                    <div class="form-group">
                        <?= $form->field($model, 'description')->textarea(['rows' => 4]); ?>
                    </div>
                     <div class="form-group">
                         <?= $form->field($model, 'readmore_link')->textInput() ?>      
                    </div>
                    <div class="form-group">
						<div style="width:100%;float:left;">
							<?= $form->field($model, 'title')->textInput() ?>      
						</div>
						
                    </div>
					
					
					
					
					<div class="form-group">	
						<div style="width:40%;float:left;">
							<?= $form->field($model, 'priority')->textInput() ?>
						</div>
						<div style="width:40%;float:left;">
							<?= $form->field($model, 'image_link')->textInput() ?>
						</div>
						<div style="width:20%;float:left;">
							<?= $form->field($model, 'status')->dropDownList(['' => 'Select Status','Active' => 'Active', 'Inactive' => 'Inactive']); ?>
						</div>
					</div>
					<div class="form-group">
						<div style="width:40%; float:left; margin-left:16px; margin-bottom:24px; margin-top:10px;">
							<label class="control-label" for="pagelayout-image">Image</label>
							<input type="file" name="image"/>
						</div>
						<div style="width:20%;float:left; margin-top:10px;">
							<label class="control-label" for="pagelayout-image">Mobile Image</label>
							<input type="file" name="mobile_image"/>
						</div>
					</div>
					<div class="form-group" style="margin-left: 20px;margin-top: 20px;">
                        <?= Html::submitButton('Create', ['class' => 'btn btn-primary', 'name' => 'create-button']) ?>
                        <?= Html::a('Cancel', ['/'.$_GET['page'].'/update?id='.$_GET['page_id'].'&type=social-action'], ['class' => 'btn btn-danger']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/social-action/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\User;
use yii\helpers\ArrayHelper;
use common\models\Utility;

$this->title = 'Social Action';
?>
<div class="panel panel-default" >
	<div class="panel-heading">
		<?php echo $this->title; ?>
		<div class="menuLink">
			<a href="<?php echo BASE_URL; ?>social-action/create?page_id=<?= $_GET['id']; ?>&type=social-action&page=<?= $page; ?>" title="Create Social Action">
				<i class="fa fa-plus-circle fa-fw" style="font-size: 18px !important;"></i>
			</a>
		</div>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			
			<?=
			GridView::widget([
				'dataProvider' => $dataProvider,
				'filterModel' => $searchModel,
				'summary' => FALSE,
				'columns' => [

					[
						'label' => 'Title',
						'attribute' => 'title',
						'value' => 'title',
						'filter' => false,
					],
					[
						'label' => 'Image',
						'attribute' => 'image',
						'format' => 'raw',
						'value' => function($dataProvider){
							if(!empty($dataProvider->image)){
								return '<img src="'.BASE_URL.'/uploads/social/'.$dataProvider->image.'" height="50" width="50"/>';
							}
						},
						'filter' => false,
					],
					[
						'label' => 'Mobile Image',
						'attribute' => 'mobile_image',
						'format' => 'raw',
						'value' => function($dataProvider){
							if(!empty($dataProvider->mobile_image)){
								return '<img src="'.BASE_URL.'/uploads/social/'.$dataProvider->mobile_image.'" height="50" width="50"/>';
							}
						},
						'filter' => false,
					],
					[
						'label' => 'Status',
						'attribute' => 'status',
						'value' => 'status',
						'filter' => false,
					],
					[
						'label' => 'Priority',
						'attribute' => 'priority',
						'value' => 'priority',
						'filter' => false,
					],
					[
						'class' => 'yii\grid\ActionColumn',
						'template' => '{update}',
						'buttons' => [
							'update' => function ($url, $searchModel) {
							return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
										'title' => Yii::t('yii', 'Update'),
							]);
						},
						],
						'urlCreator' => function ($action, $searchModel, $key, $index) {
						if ($action === 'update') {
							$page = 'pagelayout';
							if($_GET['id'] == 2){
								$page = 'focusareas';
							}if($_GET['id'] == 3){
								$page = 'project';
							}if($_GET['id'] == 4){
								$page = 'home';
							}if($_GET['id'] == 5){
								$page = 'rooftop';
							}if($_GET['id'] == 11){
								$page = 'career';
							}if($_GET['id'] == 9){
								$page = 'disclosures';
							}
							$type= "page-banners";
							if(!empty($_GET['type'])){
								$type= $_GET['type'];
							}
							$url = \Yii::$app->urlManager->createAbsoluteUrl('social-action/update' . '?id=' . $searchModel->id . '&page_id=' . $_GET['id'] . '&type='.$type.'&page='.$page);
								return $url;
							}
						}
					],
					
				],
			]);
			?>
			
		</div>
	</div>
</div>

backend/views/social-action/update.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Social Action';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-10 col-lg-offset-1">
    <div class="panel panel-default">
         <div class="panel-heading">
            <?php echo $this->title ?>
            <div class="menuLink">
                <a href="<?php echo BASE_URL; ?><?= $_GET['page']; ?>/update?id=<?= $_GET['page_id']; ?>&type=social-action" title="Social Action List">
                    <i class="fa fa-list-ul fa-fw" style="font-size: 18px !important;"></i>
                </a>
            </div>
        </div>
        <div class="panel-body">
            <div class="row table-bordered">
                <?php
                $form = ActiveForm::begin([
                            'id' => 'content_form',
                            'options' => [
                             'enctype' => 'multipart/form-data',
						],
							]
                );
                ?>            

                    <div class="form-group">
                        <?= $form->field($model, 'sec_heading')->textInput() ?>      
                    </div>
                    <div class="form-group">
                        <?= $form->field($model, 'description')->textarea(['rows' => 4]); ?>
                    </div>
                     <div class="form-group">
                         <?= $form->field($model, 'readmore_link')->textInput() ?>      
                    </div>
					 <div class="form-group">
						<div style="width:100%;float:left;">
							<?= $form->field($model, 'title')->textInput() ?>      
						</div>
						
                    </div>
					

					<div class="form-group">
						<div style="width:40%;float:left;">
							<?= $form->field($model, 'priority')->textInput() ?>
						</div>

						<div style="width:40%;float:left;">
							<?= $form->field($model, 'image_link')->textInput() ?>
						</div>
						
						 <div style="width:20%;float:left;">
							<?= $form->field($model, 'status')->dropDownList(['' => 'Select Status','Active' => 'Active', 'Inactive' => 'Inactive']); ?>
						</div>
					</div>
					<div class="form-group">
						<div style="width:20%; float:left; margin-left:12px; margin-top:10px;margin-bottom: 30px;">
							<label class="control-label" for="pagelayout-image">Image</label>
							<input type="file" name="image"/>
							<input type="hidden" name="uploaded_image" id="uploaded_image_<?= $model->id; ?>" value="<?= $model->image; ?>"/>
						</div>
						<?php if(!empty($model->image)){ ?>
						<div style="width:10%; float:left; margin-left:16px; margin-top:24px;" id="delete_img_<?= $model->id; ?>">
							<div style="position:absolute;margin-top:-11px;margin-left:42px;"><img src="<?= BASE_URL; ?>img/close.png" style="cursor:pointer;" title="Delete Image" onClick="return deleteImg('<?= $model->id; ?>');"/></div>
							<img src="<?= BASE_URL ?>/uploads/social/<?= $model->image; ?>" height="50" width="50"/>
						</div>
						<?php } ?>
						<div style="width:20%;float:left;margin-bottom: 30px; margin-top:10px;">
							<label class="control-label" for="pagelayout-image">Mobile Image</label>
							<input type="file" name="mobile_image"/>
							<input type="hidden" name="uploaded_mobile_image" id="uploaded_image_1<?= $model->id; ?>" value="<?= $model->mobile_image; ?>"/>
						</div>
						<?php if(!empty($model->mobile_image)){ ?>
						<div style="width:10%; float:left; margin-left:16px; margin-top:24px;" id="delete_img_1<?= $model->id; ?>">
							<div style="position:absolute;margin-top:-11px;margin-left:42px;"><img src="<?= BASE_URL; ?>img/close.png" style="cursor:pointer;" title="Delete Image" onClick="return deleteImg('1<?= $model->id; ?>');"/></div>
							<img src="<?= BASE_URL ?>/uploads/social/<?= $model->mobile_image; ?>" height="50" width="50"/>
						</div>
						<?php } ?>
						
					</div>
					<div class="form-group" style="margin-left: 20px;margin-top: 20px;">
                        <?= Html::submitButton('Update', ['class' => 'btn btn-primary', 'name' => 'update-button']) ?>
                        <?= Html::a('Cancel', ['/'.$_GET['page'].'/update?id='.$_GET['page_id'].'&type=page-banners'], ['class' => 'btn btn-danger']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>