backend/models/Coe.php
<?php

namespace backend\models;

use yii\data\ActiveDataProvider;
use yii\base\Model;
use Yii;

class Coe extends \yii\db\ActiveRecord {

    public static function tableName() {
        return 'coe';
    }

    public function rules() {
        return [
            [['status'], 'required'],
            [['status', 'title', 'description', 'image','mobile_image', 'sub_title'], 'safe']
        ];
    }

    public function attributeLabels() {
        return [
            'id' => 'Id',
            'title' => 'Title',
            'sub_title' => 'Sub Title',
            'description' => 'Description',
            'image' => 'Image',
            'mobile_image' => 'Mobile Image',
            'image_position' => 'Image Position',
            'status' => 'Status',
            'created_by' => 'Created By',
            'created_on' => 'Created On',
            'updated_by' => 'Updated By',
            'updated_on' => 'Updated On'
        ];
    }

    public function getContentData($id) {
		$params = '';
        $query = Coe::find()->where(['and', 'page_id='.$id])->orderBy(['title' => SORT_ASC]);
		
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
        ]);

        if (!($this->load($params))) {
            return $dataProvider;
        }
		
		$query->andFilterWhere(['like', 'title', $this->title]);
		$query->andFilterWhere(['=', 'status', $this->status]);
		
        return $dataProvider;
    }

}

backend/controllers/CoeController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\NotFoundHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\Security;
use backend\models\Coe;

/**
 * Contents controller
 */
class CoeController extends Controller{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['index', 'create', 'update'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays page layout.
     *
     * @return string
     */
    public function actionIndex(){
		$searchModel = new Coe();
		$dataProvider = $searchModel->search(Yii::$app->request->queryParams);
		
        return $this->render('index', [
				'searchModel' => $searchModel,
				'dataProvider' => $dataProvider
		]);
    }
	
	/**
     * Create new page layout.
     *
     * @return string
     */
    public function actionCreate($page_id='',$page='', $type=''){
		$model = new Coe();
		if(!empty($_POST['Coe'])){
			$model->attributes = $_POST['Coe'];
			if(!empty($_FILES['image']['name'])){
				$image_name = time().$_FILES['image']['name'];
				$image_tmp_name = $_FILES['image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'contents/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->image = $image_name;
			}
			if(!empty($_FILES['mobile_image']['name'])){
				$image_name = time().$_FILES['mobile_image']['name'];
				$image_tmp_name = $_FILES['mobile_image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'contents/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->mobile_image = $image_name;
			}
			$model->created_on = new \yii\db\Expression('now()');
			$model->created_by = Yii::$app->user->identity->id;
			$model->page_id = $page_id;
			if ($model->validate()) {
				$model->save();
				return $this->redirect(['/'.$page.'/update?id='.$page_id.'&type='.$type]);
			}		
		}		
        return $this->render('create', [
				'model' => $model
		]);
    }
	
	
	// update page layout
	public function actionUpdate($id='',$page_id='',$page='', $type=''){
		$model = $this->findModel($id);
		if(!empty($_POST['Coe'])){
			$model->attributes = $_POST['Coe'];
			$model->image = !empty($_POST['uploaded_image']) ? $_POST['uploaded_image'] : '';
			if(!empty($_FILES['image']['name'])){
				$image_name = time().$_FILES['image']['name'];
				$image_tmp_name = $_FILES['image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'contents/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->image = $image_name;
			}else{
               unset($model->image);
            }
			if(!empty($_FILES['mobile_image']['name'])){
				$image_name = time().$_FILES['mobile_image']['name'];
				$image_tmp_name = $_FILES['mobile_image']['tmp_name'];
				$image_path = IMG_UPLOAD_URL.'contents/';
				move_uploaded_file($image_tmp_name, $image_path. $image_name);
				$model->mobile_image = $image_name;
			}else{
               unset($model->mobile_image);
            }
			
			$model->updated_on = new \yii\db\Expression('now()');
			$model->updated_by = Yii::$app->user->identity->id;
			$model->page_id = $page_id;
			if ($model->validate()) {
				$model->save();
				return $this->redirect(['/'.$page.'/update?id='.$page_id.'&type='.$type]);
			}
		}
		return $this->render('update', [
				'model' => $model,
				'id' => $id
		]);
    }
	
	protected function findModel($id) {
        if (($model = Coe::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

backend/views/coe/create.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Create Centre of Excellence';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-10 col-lg-offset-1">
    <div class="panel panel-default">
         <div class="panel-heading">
            <?php echo $this->title ?>
            <div class="menuLink">
                <a href="<?php echo BASE_URL; ?><?= $_GET['page']; ?>/update?id=<?= $_GET['page_id']; ?>&type=coe" title="Centre of Excellence List">
                    <i class="fa fa-list-ul fa-fw" style="font-size: 18px !important;"></i>
                </a>
            </div>
        </div>
        <div class="panel-body">
            <div class="row table-bordered">
                <?php
                $form = ActiveForm::begin([
                            'id' => 'content_form',
                            'options' => [
                                'enctype' => 'multipart/form-data',
                            ],
                                ]
                );
                ?>            


                    <div class="form-group">
                        <?= $form->field($model, 'title')->textInput() ?>      
                    </div>
					<div class="form-group">
                        <?= $form->field($model, 'sub_title')->textInput() ?>      
                    </div>
					<div class="form-group">
                        <?= $form->field($model, 'description')->textarea(['rows' => 5, 'class' => 'left_class_editor']); ?>
                    </div>
					<div class="form-group">
						<div style="width:33%; float:left; margin-left:16px; margin-top:24px;">
                            <label>Image</label>
							<input type="file" name="image"/>
							<input type="hidden" name="uploaded_image" value="<?= $model->image; ?>"/>
						</div>
                        <div style="width:33%; float:left; margin-left:16px; margin-top:24px;">
                            <label>Mobile Image</label>
                            <input type="file" name="mobile_image"/>
                            <input type="hidden" name="uploaded_image" value="<?= $model->mobile_image; ?>"/>
                        </div>
					
						 <div style="width:30%;float:left;">
							<?= $form->field($model, 'status')->dropDownList(['' => 'Select Status','Active' => 'Active', 'Inactive' => 'Inactive']); ?>
						</div>
					</div>
                    <div class="form-group" style="margin-left: 20px;margin-top: 20px;">
                        <?= Html::submitButton('Create', ['class' => 'btn btn-primary', 'name' => 'create-button']) ?>
                        <?= Html::a('Cancel', ['/'.$_GET['page'].'/update?id='.$_GET['page_id'].'&type=coe'], ['class' => 'btn btn-danger']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

backend/views/coe/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use common\models\User;
use yii\helpers\ArrayHelper;
use common\models\Utility;

$this->title = 'Centre of Excellence ';
?>
<div class="panel panel-default" >
	<div class="panel-heading">
		<?php echo $this->title; ?>
		<div class="menuLink">
			<a href="<?php echo BASE_URL; ?>coe/create?page_id=<?= $_GET['id']; ?>&type=coe&page=<?= $page; ?>" title="Create Centre of Excellence ">
				<i class="fa fa-plus-circle fa-fw" style="font-size: 18px !important;"></i>
			</a>
		</div>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			
			<?=
			GridView::widget([
				'dataProvider' => $dataProvider,
				'filterModel' => $searchModel,
				'summary' => FALSE,
				'columns' => [

					[
						'label' => 'Title',
						'attribute' => 'title',
						'value' => 'title',
						'filter' => false,
					],
					[
						'label' => 'Sub Title',
						'attribute' => 'sub_title',
						'value' => 'sub_title',
						'filter' => false,
					],
					[
						'label' => 'Image',
						'attribute' => 'image',
						'format' => 'raw',
						'value' => function($dataProvider){
							if(!empty($dataProvider->image)){
								return '<img src="'.BASE_URL.'/uploads/contents/'.$dataProvider->image.'" height="50" width="50"/>';
							}
						},
						'filter' => false,
					],
					[
						'label' => 'Mobile Image',
						'attribute' => 'mobile_image',
						'format' => 'raw',
						'value' => function($dataProvider){
							if(!empty($dataProvider->mobile_image)){
								return '<img src="'.BASE_URL.'/uploads/contents/'.$dataProvider->mobile_image.'" height="50" width="50"/>';
							}
						},
						'filter' => false,
					],
					[
						'label' => 'Status',
						'attribute' => 'status',
						'value' => 'status',
						'filter' => false,
					],
					[
						'class' => 'yii\grid\ActionColumn',
						'template' => '{update}',
						'buttons' => [
							'update' => function ($url, $searchModel) {
							return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
										'title' => Yii::t('yii', 'Update'),
							]);
						},
						],
						'urlCreator' => function ($action, $searchModel, $key, $index) {
						if ($action === 'update') {
							$page = 'pagelayout';
							if($_GET['id'] == 2){
								$page = 'focusareas';
							}if($_GET['id'] == 3){
								$page = 'project';
							}if($_GET['id'] == 5){
								$page = 'rooftop';
							}if($_GET['id'] == 11){
								$page = 'career';
							}if($_GET['id'] == 9){
								$page = 'disclosures';
							}
							$type= "page-contents";
							if(!empty($_GET['type'])){
								$type= $_GET['type'];
							}
							$url = \Yii::$app->urlManager->createAbsoluteUrl('coe/update' . '?id=' . $searchModel->id . '&page_id=' . $_GET['id'] . '&type='.$type.'&page='.$page);
								return $url;
							}
						}
					],
				],
			]);
			?>
			
		</div>
	</div>
</div>

backend/views/coe/update.php
<?php
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = 'Update Content';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="col-lg-10 col-lg-offset-1">
    <div class="panel panel-default">
         <div class="panel-heading">
            <?php echo $this->title ?>
            <div class="menuLink">
                <a href="<?php echo BASE_URL; ?><?= $_GET['page']; ?>/update?id=<?= $_GET['page_id']; ?>&type=page-contents" title="Content List">
                    <i class="fa fa-list-ul fa-fw" style="font-size: 18px !important;"></i>
                </a>
            </div>
        </div>
        <div class="panel-body">
            <div class="row table-bordered">
                <?php
                $form = ActiveForm::begin([
                            'id' => 'content_form',
                            'options' => [
                             'enctype' => 'multipart/form-data',
						],
							]
                );
                ?>            

                    <div class="form-group">
                        <?= $form->field($model, 'title')->textInput() ?>      
                    </div>
					<div class="form-group">
                        <?= $form->field($model, 'sub_title')->textInput() ?>      
                    </div>
					<div class="form-group">
                         <?= $form->field($model, 'description')->textarea(['rows' => 5, 'class' => 'left_class_editor']); ?>
                    </div>
					<div class="form-group">
						<div style="width:33%; float:left; margin-left:16px; margin-top:24px;">
                               <label>Image</label>
							<input type="file" name="image"/>
							<input type="hidden" name="uploaded_image" id="uploaded_image_<?= $model->id; ?>" value="<?= $model->image; ?>"/>
						</div>
						<?php if(!empty($model->image)){ ?>
						<div style="width:15%; float:left; margin-left:16px; margin-top:24px;" id="delete_img_<?= $model->id; ?>">
							<div style="position:absolute;margin-top:-11px;margin-left:42px;"><img src="<?= BASE_URL; ?>img/close.png" style="cursor:pointer;" title="Delete Image" onClick="return deleteImg('<?= $model->id; ?>');"/></div>
							<img src="<?= BASE_URL ?>/uploads/contents/<?= $model->image; ?>" height="50" width="50"/>
						</div>
						<?php } ?>


                        <div style="width:33%; float:left; margin-left:16px; margin-top:24px;">
                               <label>Mobile Image</label>
                            <input type="file" name="mobile_image"/>
                            <input type="hidden" name="uploaded_image" id="uploaded_image_<?= $model->id; ?>" value="<?= $model->mobile_image; ?>"/>
                        </div>
                        <?php if(!empty($model->mobile_image)){ ?>
                        <div style="width:15%; float:left; margin-left:16px; margin-top:24px;" id="delete_img_<?= $model->id; ?>">
                            <div style="position:absolute;margin-top:-11px;margin-left:42px;"><img src="<?= BASE_URL; ?>img/close.png" style="cursor:pointer;" title="Delete Image" onClick="return deleteImg('<?= $model->id; ?>');"/></div>
                            <img src="<?= BASE_URL ?>/uploads/contents/<?= $model->mobile_image; ?>" height="50" width="50"/>
                        </div>
                        <?php } ?>
						
						
					</div>
                            <div class="form-group">
                     <div style="width:20%;float:left;">
                            <?= $form->field($model, 'status')->dropDownList(['' => 'Select Status','Active' => 'Active', 'Inactive' => 'Inactive']); ?>
                        </div>
                    </div>
                    <div class="form-group" style="margin-left: 20px;margin-top: 20px;">
                        <?= Html::submitButton('Update', ['class' => 'btn btn-primary', 'name' => 'update-button']) ?>
                        <?= Html::a('Cancel', ['/'.$_GET['page'].'/update?id='.$_GET['page_id'].'&type=page-contents'], ['class' => 'btn btn-danger']) ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>